server:
  port: 8961

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallback
    config:
      uri: http://localhost:8861
      enabled: true
  config:
    import: "optional:configserver:"


#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  serviceUrl:
#    defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
